name: bookkeeping
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  json_annotation: ^3.0.0

    # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.0
  # 网络库 https://github.com/flutterchina/dio
  dio: ">=2.1.0 <6.0.0"
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # 加载指示器https://github.com/jogboms/flutter_spinkit
  flutter_spinkit: ^3.1.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^0.3.10+4
  # 屏幕适配方案https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^0.5.3
  # 数据库 https://pub.flutter-io.cn/packages/sqflite
  sqflite: ^1.1.6
  # 路径插件 https://pub.dev/packages/path_provider
  path_provider: ^1.2.0
  # 列表悬浮头 https://github.com/fluttercommunity/flutter_sticky_headers
  # sticky_headers: ^0.1.8
  # 时间选择器 https://github.com/Realank/flutter_datetime_picker
  flutter_datetime_picker: ^1.2.6
  # google的图表库 https://github.com/google/charts
  charts_flutter: ^0.8.1
  # https://pub.dev/packages/intl
  intl: ^0.15.2

dev_dependencies:
  # Your other dev_dependencies here
  flutter_test:
    sdk: flutter

  build_runner: ^1.6.7
  json_serializable: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/icons/
    - assets/images/category/car/
    - assets/images/category/catering/
    - assets/images/category/housing/
    - assets/images/category/humanfeelings/
    - assets/images/category/income/
    - assets/images/category/other/
    - assets/images/category/shopping/
    - assets/images/category/traffic/
    - assets/images/category/daily/
    - assets/images/category/recreation/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
